general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrains Mono NL" }
bold = { family = "JetBrains Mono NL" }
italic = { family = "JetBrains Mono NL" }
size = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[mouse]
bindings = [
{ mouse = "Right", action = "Copy" },
{ mouse = "Middle", action = "Paste" }
]
